on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Workflow failed"}' 
          ${{ secerets.SLACK_WEBHOOK_URL }}

 #curl -X POST -H 'Content-type: application/json' \
 #         --data '{"text": "🚨 Workflow \"Publish to Docker\" in repository *${{ github.repository }}* failed.\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View details here>."}' \
 #         ${{ secrets.SLACK_WEBHOOK_URL }}
